server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/auth/**
        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/v1/parking/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
