server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
#            - Path=/api/v1/auth/**
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/api/v1/parking/**
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/v1/vehicle/**
        - id: payment-service
          uri: lb://PAYMENT_SERVICE
          predicates:
            - Path=/api/v1/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
