server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nimsimethusala/AD2-Parking-Management-System.git
          clone-on-start: true
          default-label: main
          username: username
          password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
